### ISSUE TITLE
Login Auth

### ISSUE THREAD

**Issue by steventhanna** [steventhanna/phoenix-suns-radio#1]
Problem with Login authentication.  Signup auth seems to be working fine.
## Code

This snippet resides within the `AuthController.js`.

``` js
login: function(req, res) {
    passport.authenticate('local', function(err, user, info) {
      if (err || (!user)) {
        console.log("user = " + user);
        console.log("err = " + err);
        console.log("info = ");
        console.log(info);

        res.send({
          success: false,
          error: true,
          errorMessage: "This user does not exist or there was some sort of error. ",
          info: info
        });
      } else if ((!err) && user) {
        req.logIn(user, function(err) {
          if (err) {
            console.log("There was an error logging the user.");
            console.log("Error = " + err);
            console.log("Error Code 0002.0");
            console.log("Users Account: ");
            console.log(user);
            res.serverError();
            return;
          } else {
            res.send({
              success: true
            });
          }
        });
      } else {
        res.send({
          success: false
        });
      }
    })(req, res);
  },
```

**Note**: It is possible that passport is trying to look for the user on the database through a username, instead of an email address.  This could be the problem.
## Error Message

```
user = false
err = null
info = 
{ message: 'Missing credentials' }
```

**Comment by steventhanna** [comment]
For some reason, after I implemented unit tests, the login function always sends a 200 status error... Even though I am sending `res.serverError()` and `500` errors.

```
error: Sending empty 500 ("Server Error") response
․user = false
err = null
info = 
{ message: 'Missing credentials' }
error: Sending empty 500 ("Server Error") response
․user = false
err = null
info = 
{ message: 'Missing credentials' }
error: Sending empty 500 ("Server Error") response
․․․․

  6 passing (2s)
  1 failing

  1) AuthController #login should fail to login to an account:
     Error: expected 500 "Internal Server Error", got 200 "OK"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at net.js:1419:10
```

To get the tests, just run `npm test` or check them out on travis.

**Comment by steventhanna** [comment]
Additionally, check [travis](https://travis-ci.org/steventhanna/phoenix-suns-radio/jobs/87829899) error messages... Seems to be an error comparing passwords.

**Comment by steventhanna** [comment]
Now, login works right after user creation.  I think that I have isolated the issue to the login function, or the session auth... Because in order for the system to login a user after creation successfully, it might need that information...

**Comment by steventhanna** [comment]
I reorganized when error codes are sent in `login`, and now the unit tests pass... Still unable to login though.
